name: DCU CI Runner Action
description: Create DCU CICD runner
inputs:
  aws-access-key:
    description: AWS Access key
    required: true
  aws-secret-key:
    description: AWS secret key
    required: true
  aws-deploy-role:
    description: AWS deploy role arn
    required: true
  repo-pat:
    description: Github PAT with access to the local repo
    required: true
  custom-user-data:
    description: Custom shell script to be passed as user data
    required: false
    default: "echo 'No Custom UserData'"
  use-cicd-role:
    description: Github PAT with access to the local repo
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        mkdir -p ~/.aws/
        echo "[cicd]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ inputs.aws-access-key }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ inputs.aws-secret-key }}" >> ~/.aws/credentials
        echo "role_arn=${{ inputs.aws-deploy-role }}" >> ~/.aws/credentials
        echo "duration_seconds=900" >> ~/.aws/credentials

        echo "[profile cicd]" > ~/.aws/config
        echo "region=us-west-2" >> ~/.aws/config
        echo "output=json" >> ~/.aws/config
        echo "source_profile=cicd" >> ~/.aws/config
    - shell: bash
      env:
        ACTION_PATH: "./local-actions/runner-autoscaling"
        MODE: "start"
        GITHUB_TOKEN: "${{ inputs.repo-pat }}"
        TTL: "4 hour"
        NEEDS_DX: "true"
        GH_EVENT_REF: ${{ github.event.ref }}
        RUNNER_INSTANCE_TYPE: "t3.small"
        RUNNER_AMI_ID: "/GoldenAMI/gd-ubuntu20.04/latest"
        RUNNER_VOLUME_SIZE: "100"
        RUNNER_DEVICE_NAME: "/dev/sda1"
        RUNNER_LABELS: "ec2ubuntu"
        USE_CICD_ROLE: "${{ inputs.use-cicd-role }}"
        DESIRED_SIZE: 1
        DESIRED_RUNNER_NAME: ''
        CUSTOM_USER_DATA: "${{ inputs.custom-user-data }}"
      run: |
        export AWS_PROFILE=cicd
        export AWS_REGION='us-west-2'
        git clone https://${{ inputs.repo-pat }}:x-oauth-basic@github.com/gdcorp-actions/runner-autoscaling.git local-actions/runner-autoscaling
        cd local-actions/runner-autoscaling && git checkout v1.11.0 && cd ../..
        pip install 'requests>=2.25,<3' --force-reinstall
        pip install sceptre
        ACTION_PATH="$PWD/local-actions/runner-autoscaling" local-actions/runner-autoscaling/autoscale.sh
    - shell: bash
      run: rm -rf local-actions/runner-autoscaling
