name: DCU CI Runner Action
description: Create DCU CICD runner
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cat > ~/.aws/credentials <<
        [CICD]
        aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID_CICD }}
        aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY_CICD }}
        role_arn=${{ secrets.AWS_DEPLOY_ROLE_CICD }}
        duration_seconds=900

        EOF
        cat > ~/.aws/config <<
        [CICD]
        region=us-west-2
        output=json

        EOF
    - shell: bash
      run: |
        export AWS_PROFILE=CICD
        git clone https://${{ secrets.REPO_PAT }}:x-oauth-basic@github.com/gdcorp-actions/runner-autoscaling.git local-actions/runner-autoscaling
        cd local-actions/runner-autoscaling && git checkout v2
        pip install -r local-actions/runner-autoscaling/requirements.txt
        local-actions/runner-autoscaling/autoscale.sh "local-actions/runner-autoscaling" "start" "${{ secrets.REPO_PAT }}" "4 hour" "true" "ec2ubuntu" "t3.small" "/GoldenAMI/gd-ubuntu20.04/latest" "20" "${{ github.event.ref }}" "/dev/xvda"
