name: DCU CI Runner Action
description: Create DCU CICD runner
inputs:
  aws-access-key:
    description: AWS Access key
    required: true
  aws-secret-key:
    description: AWS secret key
    required: true
  aws-deploy-role:
    description: AWS deploy role arn
    required: true
  repo-pat:
    description: Github PAT with access to the local repo
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        mkdir -p ~/.aws/
        echo "[cicd]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ inputs.aws-access-key }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ inputs.aws-secret-key }}" >> ~/.aws/credentials
        echo "role_arn=${{ inputs.aws-deploy-role }}" >> ~/.aws/credentials
        echo "duration_seconds=900" >> ~/.aws/credentials

        echo "[profile cicd]" > ~/.aws/config
        echo "region=us-west-2" >> ~/.aws/config
        echo "output=json" >> ~/.aws/config
        echo "source_profile=cicd" >> ~/.aws/config
    - shell: bash
      run: |
        export AWS_PROFILE=cicd
        export AWS_REGION='us-west-2'
        git clone https://${{ inputs.repo-pat }}:x-oauth-basic@github.com/gdcorp-actions/runner-autoscaling.git local-actions/runner-autoscaling
        cd local-actions/runner-autoscaling && git checkout v1.6.1 && cd ../..
        pip install -r local-actions/runner-autoscaling/requirements.txt
        ACTION_PATH="$PWD/local-actions/runner-autoscaling/" local-actions/runner-autoscaling/autoscale.sh "$PWD/local-actions/runner-autoscaling" "start" "${{ inputs.repo-pat }}" "4 hour" "true" "ec2ubuntu" "t3.small" "/GoldenAMI/gd-ubuntu20.04/latest" "20" "${{ github.event.ref }}" "/dev/xvda" "false"
