name: DCU Python CI Action
description: Perform basic python integration actions.
inputs:
  full-stretch:
    required: false
    default: true
runs:
  using: composite
  steps:
    - shell: bash
      id: secrets
      run: |
        SECRET=$(aws secretsmanager get-secret-value --secret-id '/GitHub/GitHub-Actions-Runner-PAT' --query 'SecretString' --output text)
        PAT=$(echo ${SECRET} | jq -r .PAT)
        echo "::set-output name=pat::${PAT}"
        echo "::add-mask::$PAT"
        SECRET=$(aws secretsmanager get-secret-value --secret-id '/CICD/artifactory' --query 'SecretString' --output text)
        USERNAME=$(echo ${SECRET} | jq -r .username)
        PASSWORD=$(echo ${SECRET} | jq -r .password)
        echo "::set-output name=artifactory-username::${USERNAME}"
        echo "::add-mask::$USERNAME"
        echo "::set-output name=artifactory-password::${PASSWORD}"
        echo "::add-mask::$PASSWORD"
    - shell: bash
      run: |
        python -m venv .venv && source .venv/bin/activate
        pip install flake8==3.9.2 isort==4.3.4 importlib-metadata==4.6.1

        flake8 --config ./.flake8 .

        if [[ "${{inputs.full-stretch}}" == "true" ]];
        then
          mkdir -p ~/.pip
          echo "[distutils]" > ~/.pypirc
          echo "index-servers = local" >> ~/.pypirc
          echo "[local]" >> ~/.pypirc
          echo "repository: https://artifactory.secureserver.net/artifactory/api/pypi/pypi-digital-crimes-unit-main-local" >> ~/.pypirc
          echo "username: ${{ steps.secrets.outputs.artifactory-username }}" >> ~/.pypirc
          echo "password: ${{ steps.secrets.outputs.artifactory-password }}" >> ~/.pypirc

          echo "[global]" > ~/.pip/pip.conf
          echo "index-url = https://${{ steps.secrets.outputs.artifactory-username }}:${{ steps.secrets.outputs.artifactory-password }}@artifactory.secureserver.net/artifactory/api/pypi/python-virt/simple" >> ~/.pip/pip.conf

          [ -f Makefile ] && make env || exit 0

          [ -f Makefile ] && make tools

          # We expect one change - a folder called local-actions.
          [ -f Makefile ] && if [[ `git status --porcelain | wc -l` -gt 1 ]] ; then echo "imports not run through isort" ; exit 1 ; fi

          [ -f Makefile ] && make test
        fi

        deactivate
        rm -rf .venv/
