name: DCU Python CI Action
description: Perform basic python integration actions.
runs:
  using: composite
  steps:
    - shell: bash
      id: secrets
      run: |
        SECRET=$(aws secretsmanager get-secret-value --secret-id '/GitHub/GitHub-Actions-Runner-PAT' --query 'SecretString' --output text)
        PAT=$(echo ${SECRET} | jq -r .PAT)
        echo "::set-output name=pat::${PAT}"
        echo "::add-mask::$PAT"
        SECRET=$(aws secretsmanager get-secret-value --secret-id '/CICD/artifactory' --query 'SecretString' --output text)
        USERNAME=$(echo ${SECRET} | jq -r .username)
        PASSWORD=$(echo ${SECRET} | jq -r .password)
        echo "::set-output name=artifactory-username::${USERNAME}"
        echo "::add-mask::$USERNAME"
        echo "::set-output name=artifactory-password::${PASSWORD}"
        echo "::add-mask::$PASSWORD"
    - shell: bash
      run: |
        git clone https://${{ steps.secrets.outputs.pat }}:x-oauth-basic@github.com/gdcorp-actions/tartufo.git .tartufo
        cd .tartufo && git checkout v3.2.0 && cd ..
        export GITHUB_WORKSPACE=/tartufo_action
        export INPUT_GITHUB_TOKEN=${{ steps.secrets.outputs.pat }}
        export INPUT_CURRENT_EVENT_ONLY=true
        docker run --env-file <(env) -v $PWD:/repo -v $GITHUB_EVENT_PATH:$GITHUB_EVENT_PATH -v $PWD/.tartufo:/tartufo_action --entrypoint /tartufo_action/entrypoint.py 764525110978.dkr.ecr.us-west-2.amazonaws.com/alpine-tartufo:v2.5.0
        rm -rf .tartufo
    - shell: bash
      run: |
        python -m venv .venv && source .venv/bin/activate
        pip install flake8==3.9.2 isort==4.3.4

        flake8 --config ./.flake8 .

        if [[ ! -z "${{ steps.secrets.outputs.artifactory-password }}" ]];
        then
          mkdir -p ~/.pip
          echo "[distutils]" > ~/.pypirc
          echo "index-servers = local" >> ~/.pypirc
          echo "[local]" >> ~/.pypirc
          echo "repository: https://artifactory.secureserver.net/artifactory/api/pypi/pypi-digital-crimes-unit-main-local" >> ~/.pypirc
          echo "username: ${{ steps.secrets.outputs.artifactory-username }}" >> ~/.pypirc
          echo "password: ${{ steps.secrets.outputs.artifactory-password }}" >> ~/.pypirc

          echo "[global]" > ~/.pip/pip.conf
          echo "index-url = https://ci_ro_infosec-dcu:${{ steps.secrets.outputs.artifactory-password }}@artifactory.secureserver.net/artifactory/api/pypi/python-virt/simple" >> ~/.pip/pip.conf

          [ -f Makefile ] && make env

          [ -f Makefile ] && make tools

          # We expect one change - a folder called local-actions.
          [ -f Makefile ] && if [[ `git status --porcelain | wc -l` -gt 1 ]] ; then echo "imports not run through isort" ; exit 1 ; fi

          [ -f Makefile ] && make test
        fi

        deactivate
        rm -rf .venv/
