name: DCU Python Pip Push
description: Build the python package and push it to the DCU artifactory.
runs:
  using: composite
  steps:
    - shell: bash
      id: secrets
      run: |
        SECRET=$(aws secretsmanager get-secret-value --region us-west-2 --secret-id '/CICD/pypi-artifactory-rw-user' --query 'SecretString' --output text)
        USERNAME=$(echo ${SECRET} | jq -r .username)
        PASSWORD=$(echo ${SECRET} | jq -r .password)
        echo "::set-output name=artifactory-username::${USERNAME}"
        echo "::add-mask::$USERNAME"
        echo "::set-output name=artifactory-password::${PASSWORD}"
        echo "::add-mask::$PASSWORD"
    - shell: bash
      run: |
        export PATH=$HOME/.local/bin:$PATH
        curl -sSL https://install.python-poetry.org | python -
        poetry config http-basic.gddy ${{ steps.secrets.outputs.artifactory-username }} ${{ steps.secrets.outputs.artifactory-password }}
        poetry config repositories.cset https://artifactory.secureserver.net/artifactory/api/pypi/pypi-digital-crimes-unit-main-local
        rm poetry.lock
        poetry install
        make build
        poetry publish -r cset -u ${{ steps.secrets.outputs.artifactory-username }} -p ${{ steps.secrets.outputs.artifactory-password }}
