name: DCU Go CI Action
description: Perform basic python integration actions.
inputs:
  aws-access-key:
    description: AWS Access key
    required: true
  aws-secret-key:
    description: AWS secret key
    required: true
  aws-deploy-role:
    description: AWS deploy role arn
    required: true
  repo-pat:
    description: Github PAT with access to the local repo
    required: true
  main-path:
    description: Main path of the go repo
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        mkdir -p ~/.aws/
        echo "[cicd]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ inputs.aws-access-key }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ inputs.aws-secret-key }}" >> ~/.aws/credentials
        echo "role_arn=${{ inputs.aws-deploy-role }}" >> ~/.aws/credentials
        echo "duration_seconds=900" >> ~/.aws/credentials

        echo "[profile cicd]" > ~/.aws/config
        echo "region=us-west-2" >> ~/.aws/config
        echo "output=json" >> ~/.aws/config
        echo "source_profile=cicd" >> ~/.aws/config
    - shell: bash
      run: |
        export AWS_PROFILE=cicd
        export AWS_REGION='us-west-2'
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 764525110978.dkr.ecr.us-west-2.amazonaws.com
    - shell: bash
      run: |
        git clone https://${{ inputs.repo-pat }}:x-oauth-basic@github.com/gdcorp-actions/tartufo.git .tartufo
        cd .tartufo && git checkout v3.2.0 && cd ..
        export GITHUB_WORKSPACE=/tartufo_action
        export INPUT_GITHUB_TOKEN=${{ inputs.repo-pat }}
        export INPUT_CURRENT_EVENT_ONLY=true
        docker run --env-file <(env) -v $PWD:/repo -v $GITHUB_EVENT_PATH:$GITHUB_EVENT_PATH -v $PWD/.tartufo:/tartufo_action --entrypoint /tartufo_action/entrypoint.py 764525110978.dkr.ecr.us-west-2.amazonaws.com/alpine-tartufo:v2.5.0
        rm -rf .tartufo
    - shell: bash
      run: |
        go env -w GOPRIVATE="github.com/gdcorp-infosec/*"
        git config --global url."https://${{ inputs.repo-pat }}:x-oauth-basic@github.com/gdcorp-infosec".insteadOf "https://github.com/gdcorp-infosec"
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -i -v -o build/build ${{ inputs.main-path }}
        go test -v ./...
