name: DCU Go CI Action
description: Perform basic python integration actions.
inputs:
  main-path:
    description: Main path of the go repo
    required: true
  compile:
    description: Attempt to compile the go binary in main path.
    required: true
    default: true
runs:
  using: composite
  steps:
    - shell: bash
      id: secrets
      run: |
        SECRET=$(aws secretsmanager get-secret-value --secret-id '/GitHub/GitHub-Actions-Runner-PAT' --query 'SecretString' --output text)
        PAT=$(echo ${SECRET} | jq -r .PAT)
        echo "::set-output name=pat-cloud::${PAT}"
        echo "::add-mask::$PAT"
        SECRET=$(aws secretsmanager get-secret-value --secret-id '/KeePass/github-pat/secureserver' --query 'SecretString' --output text)
        PREMISE_PAT=$(echo ${SECRET} | jq -r .pat)
        echo "::set-output name=pat-onpremise::${PREMISE_PAT}"
        echo "::add-mask::$PREMISE_PAT"
    - shell: bash
      run: |
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 764525110978.dkr.ecr.us-west-2.amazonaws.com
        git clone https://${{ steps.secrets.outputs.pat-cloud }}:x-oauth-basic@github.com/gdcorp-actions/tartufo.git .tartufo
        cd .tartufo && git checkout v3.2.0 && cd ..
        export GITHUB_WORKSPACE=/tartufo_action
        export INPUT_GITHUB_TOKEN=${{ steps.secrets.outputs.pat-cloud }}
        export INPUT_CURRENT_EVENT_ONLY=true
        docker run --env-file <(env) -v $PWD:/repo -v $GITHUB_EVENT_PATH:$GITHUB_EVENT_PATH -v $PWD/.tartufo:/tartufo_action --entrypoint /tartufo_action/entrypoint.py 764525110978.dkr.ecr.us-west-2.amazonaws.com/alpine-tartufo:v2.5.0
        rm -rf .tartufo
    - shell: bash
      run: |
        go env -w GOPRIVATE="github.com/gdcorp-infosec/*,github.secureserver.net/*"
        git config --global url."https://${{ steps.secrets.outputs.pat-cloud }}:x-oauth-basic@github.com/gdcorp-infosec".insteadOf "https://github.com/gdcorp-infosec"
        git config --global url."https://${{ steps.secrets.outputs.pat-onpremise }}:x-oauth-basic@github.secureserver.net".insteadOf "https://github.secureserver.net"
        go get -u golang.org/x/lint/golint
        golint ./...
        go test -v ./...
    - shell: bash
      run: |
        if [[ "${{inputs.compile}}" == "true" ]]; then
          go env -w GOPRIVATE="github.com/gdcorp-infosec/*,github.secureserver.net/*"
          git config --global url."https://${{ steps.secrets.outputs.pat-cloud }}:x-oauth-basic@github.com/gdcorp-infosec".insteadOf "https://github.com/gdcorp-infosec"
          git config --global url."https://${{ steps.secrets.outputs.pat-onpremise }}:x-oauth-basic@github.secureserver.net".insteadOf "https://github.secureserver.net"
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -i -v -o build/build ${{ inputs.main-path }}
        fi
