name: DCU Go CI Action
description: Perform basic python integration actions.
inputs:
  main-path:
    description: Main path of the go repo
    required: true
  compile:
    description: Attempt to compile the go binary in main path.
    required: true
    default: true
runs:
  using: composite
  steps:
    - shell: bash
      id: secrets
      run: |
        SECRET=$(aws secretsmanager get-secret-value --secret-id '/GitHub/GitHub-Actions-Runner-PAT' --query 'SecretString' --output text)
        PAT=$(echo ${SECRET} | jq -r .PAT)
        echo "::set-output name=pat-cloud::${PAT}"
        echo "::add-mask::$PAT"
        SECRET=$(aws secretsmanager get-secret-value --secret-id '/KeePass/github-pat/secureserver' --query 'SecretString' --output text)
        PREMISE_PAT=$(echo ${SECRET} | jq -r .pat)
        echo "::set-output name=pat-onpremise::${PREMISE_PAT}"
        echo "::add-mask::$PREMISE_PAT"
    - shell: bash
      run: |
        go env -w GOPRIVATE="github.com/gdcorp-infosec/*,github.secureserver.net/*"
        git config --global url."https://${{ steps.secrets.outputs.pat-cloud }}:x-oauth-basic@github.com/gdcorp-infosec".insteadOf "https://github.com/gdcorp-infosec"
        git config --global url."https://${{ steps.secrets.outputs.pat-onpremise }}:x-oauth-basic@github.secureserver.net".insteadOf "https://github.secureserver.net"
        go get -u golang.org/x/lint/golint
        golint ./...
        go test -v ./...
    - shell: bash
      run: |
        if [[ "${{inputs.compile}}" == "true" ]]; then
          go env -w GOPRIVATE="github.com/gdcorp-infosec/*,github.secureserver.net/*"
          git config --global url."https://${{ steps.secrets.outputs.pat-cloud }}:x-oauth-basic@github.com/gdcorp-infosec".insteadOf "https://github.com/gdcorp-infosec"
          git config --global url."https://${{ steps.secrets.outputs.pat-onpremise }}:x-oauth-basic@github.secureserver.net".insteadOf "https://github.secureserver.net"
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -i -v -o build/build ${{ inputs.main-path }}
        fi
