name: DCU Python CI Action
description: Perform basic python integration actions.
inputs:
  repo-pat:
    description: Github PAT with access to the local repo
    required: true
  artifactory-password:
    description: CI RO user artifactory password.
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        export PATH=$HOME/.local/bin:$PATH
        export LD_LIBRARY_PATH="/usr/local/lib/:$PWD/../../_tool/Python/3.7.10/x64/lib"
        python3 -m pip install --user pipx poetry tartufo
        python3 -m pipx ensurepath
        poetry config http-basic.gddy-artifactory ci_ro_infosec-dcu ${{ inputs.artifactory-password }}
        poetry config http-basic.gddy ci_ro_infosec-dcu ${{ inputs.artifactory-password }}
        rm poetry.lock
        make init
        make lint
        tartufo scan-local-repo --branch $(git rev-parse --abbrev-ref HEAD) .
        # We expect one change - a folder called local-actions.
        git checkout -- package.json ||:
        if [[ `git status --porcelain | wc -l` -gt 1 ]] ; then echo "Failed lint checks" ; exit 1 ; fi
        make unit-test
