name: DCU Python CI Action
description: Perform basic python integration actions.
inputs:
  repo-pat:
    description: Github PAT with access to the local repo
    required: true
  artifactory-password:
    description: CI RO user artifactory password.
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        export PATH=$HOME/.local/bin:$PATH
        export POETRY_HTTP_BASIC_GDDY_USERNAME="ci_ro_infosec-dcu"
        export POETRY_HTTP_BASIC_GDDY_PASSWORD="${{ inputs.artifactory-password }}"
        python3 -m pip install --user pipx tartufo
        python3 -m pipx ensurepath
        pipx install poetry
        make init
        make lint
        tartufo scan-local-repo .
        # We expect one change - a folder called local-actions.
        git checkout -- package.json ||:
        git checkout -- poetry.lock ||:
        if [[ `git status --porcelain | wc -l` -gt 1 ]] ; then echo "Failed lint checks" ; exit 1 ; fi
        make unit-test
