name: DCU Python CI Action
description: Perform basic python integration actions.
runs:
  using: composite
  steps:
    - name: Get Secrets
      id: secrets
      run: |
        SECRET=$(aws secretsmanager get-secret-value --secret-id '/CICD/artifactory' --query 'SecretString' --output text)
        USERNAME=$(echo ${SECRET} | jq -r .username)
        PASSWORD=$(echo ${SECRET} | jq -r .password)
        echo "::set-output name=artifactory-username::${USERNAME}"
        echo "::add-mask::$USERNAME"
        echo "::set-output name=artifactory-password::${PASSWORD}"
        echo "::add-mask::$PASSWORD"
    - shell: bash
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        export PATH=$HOME/.local/bin:$PATH
        export POETRY_HTTP_BASIC_GDDY_USERNAME="${{ steps.secrets.outputs.artifactory-username }}"
        export POETRY_HTTP_BASIC_GDDY_PASSWORD="${{ steps.secrets.outputs.artifactory-password }}"
        python3 -m pip install --user pipx tartufo
        python3 -m pipx ensurepath
        pipx install poetry
        make init
        make lint
        tartufo scan-local-repo .
        # We expect one change - a folder called local-actions.
        git checkout -- package.json ||:
        git checkout -- poetry.lock ||:
        if [[ `git status --porcelain | wc -l` -gt 1 ]] ; then echo "Failed lint checks" ; exit 1 ; fi
        make unit-test
