name: DCU Python CI Action
description: Perform basic python integration actions.
inputs:
  aws-access-key:
    description: AWS Access key
    required: true
  aws-secret-key:
    description: AWS secret key
    required: true
  aws-deploy-role:
    description: AWS deploy role arn
    required: true
  repo-pat:
    description: Github PAT with access to the local repo
    required: true
  artifactory-password:
    description: CI RO user artifactory password.
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        mkdir -p ~/.aws/
        echo "[CICD]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ inputs.aws-access-key }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ inputs.aws-secret-key }}" >> ~/.aws/credentials
        echo "role_arn=${{ inputs.aws-deploy-role }}" >> ~/.aws/credentials
        echo "duration_seconds=900" >> ~/.aws/credentials

        echo "[CICD]" > ~/.aws/config
        echo "region=us-west-2" >> ~/.aws/config
        echo "output=json" >> ~/.aws/config
    - shell: bash
      run: |
        export AWS_PROFILE=CICD
        export AWS_REGION='us-west-2'
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 764525110978.dkr.ecr.us-west-2.amazonaws.com
    - shell: bash
      run: |
        git clone https://${{ inputs.repo-pat }}:x-oauth-basic@github.com/gdcorp-actions/tartufo.git .tartufo
        INPUT_GITHUB_TOKEN=${{ inputs.repo-pat }} python .tartufo/entrypoint.py
    - shell: bash
      run: |
        mkdir -p ~/.pip/
        echo "[global]" > ~/.pip/pip.conf
        echo "index-url = https://ci_ro_infosec-dcu:${{ inputs.artifactory-password }}@artifactory.secureserver.net/artifactory/api/pypi/python-virt/simple" >> ~/.pip/pip.conf
        python -m venv .venv && source .venv/bin/activate
        pip install -r tools.txt -r requirements.txt
        flake8 .
        nosetests test/
